name: Auto Merge

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.15.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge_method: squash
          required_labels: automerge
          delete_branch: true
